### PR TITLE
mapname fix

### PR DESCRIPTION
**Pull request by xCorteX**
update to get Mapname + added new offset

### CODE REVIEW

**Comment by rabume** [comment]
@xCorteX Very nice. Thanks :pray: 
Will check it out soon

**Comment by xCorteX** [comment]
Tonight I will add life points to the icon and team colors ✌️

**Comment by xCorteX** [comment]
https://github.com/user-attachments/assets/b7d03818-ba33-4616-8e3d-c47029a96b1e

**Comment by rabume** [comment]
Very nice 👍 Just merged your change

**Pull request merged**
